server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ayqjbwsqralpwjtarenu.supabase.co/auth/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

orkestra:
  stage: local
  aws:
    region: us-east-1
    local: true
    accessKey: test
    secretKey: test
  dynamodb:
    endpoint: http://localhost:4566
    tables:
      jobDefinitions: ${orkestra.stage}_orkestra_job_definitions
      workflowIndex: ${orkestra.stage}_orkestra_workflow_index
      platformAdmins: ${orkestra.stage}_orkestra_platform_admins
      tenants: ${orkestra.stage}_orkestra_tenants
      tenantMemberships: ${orkestra.stage}_orkestra_tenant_memberships

